### ISSUE TITLE
BeeRich remix.init script fails

### ISSUE THREAD

**Issue by andrelandgraf** [PacktPublishing/Full-Stack-Web-Development-with-Remix#125]
**Describe the bug**

BeeRich's remix.init script fails due to an ESM error.

**Actual behavior**

`create-remix` fails to execute the init script:

```bash
  init   This template has a remix.init script. Do you want to run it?
         Yes

      ✔  Dependencies installed

      ✔  Git initialized

      ◼  Running template's remix.init script... 


      ▲  Oh no! Template's remix.init script failed
```

**Expected behavior**

`Hey there! Great job practicing using a custom stack! You're doing great!` should be logged to the console when running:

- `npx create-remix@2 --template <bee-rich GitHub URL>` to bootstrap the application
- `npx remix init` in the root of the BeeRich project after bootstrapping the application

**Comment by andrelandgraf** [comment]
Reported the issue to the Remix team: https://github.com/remix-run/remix/issues/7951.

**Comment by andrelandgraf** [comment]
Hopefully fixed via https://github.com/remix-run/remix/pull/8100

**Comment by riiiiion** [comment]
I had a similar problem myself.

If I add a package.json to the remix.init folder with the following description
I was able to run `npx remix init` without any problems.

```json:package.json
{
  "type": "commonjs"
}

```

**Comment by andrelandgraf** [comment]
Thanks! I was hoping `create-remix` could fix this internally. Is this still happening on v2.10? I guess adding the `package.json` is a good enough fix for this repo. Will make an update this weekend. 🙏

**Comment by andrelandgraf** [comment]
Thanks for reminding me to fix this, @riiiiion. 😅
