### ISSUE TITLE
Minor typographical changes

### ISSUE THREAD

**Issue by erryte** [PacktPublishing/Full-Stack-Web-Development-with-Remix#126]
Page: [100] #7 - export async function action({ request }: ActionArgs)  --> "ActionFunctionArgs"
Page: [110] #8 - dashboard.expenses.index.tsx --> dashboard.expenses._index.tsx

**Comment by andrelandgraf** [comment]
Confirmed that those have been fixed in the final eBook and print versions! Thanks again for reporting, Terry! 🙏
